import React, { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Card,
  Flex,
  Stack,
  SimpleGrid,
  Text,
  Center,
  Image,
  CardHeader,
  CardBody,
  CardFooter,
  Button,
  Spacer,
} from "@chakra-ui/react";
import Checkbox from "@/components/Checkbox";
import axios from "axios";
function address() {
  const [address,setAddress] = useState([]);
  useEffect(() => {
    async function fetchdata() {
      let user_id = 1;
      const formdata = new FormData();
      formdata.append("user_id",user_id);
      const res = await axios.post(
        `https://shopee-api.deksilp.com/api/getAddress`,formdata
      )
      setAddress(res.data.address);
    }

    fetchdata();
  },[])
  
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="25px">
        <Box px="35px">
          <Text fontSize="xl">ที่อยู่</Text>
        </Box>
      </Box>
      <Box py="10px" mt="10px" bg="white">
        <Checkbox data={address} />
        <Flex justifyContent="center">
          <Link href="/address/newaddress">
            <Button bg="red">
              <Text>เพิ่มที่อยู่ใหม่</Text>
            </Button>
          </Link>
        </Flex>
      </Box>
    </>
  );
}

export default address;
