import react, { useState, useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Card,
  Flex,
  Grid,
  SimpleGrid,
  Text,
  GridItem,
  Image,
  CardHeader,
  CardBody,
  CardFooter,
  Button,
  Spacer,
} from "@chakra-ui/react";
import CartItem from "@/components/CartItem";
import axios from "axios";
function useChartShop() {
  const [cartsItem, setCartsItem] = useState([]);
  useEffect(() => {
    async function fetchData() {
      const carts = await axios.get(
        `https://shopee-api.deksilp.com/api/getAllCartItem/1`
      );
      setCartsItem(carts.data);
    }
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cartsItem.length !== 0 ? <CartItem data={cartsItem} /> : null}
    </>
  );
}

export default useChartShop;
