import react, { useState, useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Card,
  Flex,
  Grid,
  SimpleGrid,
  Text,
  GridItem,
  Image,
  CardHeader,
  CardBody,
  CardFooter,
  Button,
  Spacer,
} from "@chakra-ui/react";
import CartItem from "@/components/CartItem";
import axios from "axios";
import { useSelector } from "react-redux";
function useChartShop() {
  const [cartsItem, setCartsItem] = useState([]);
  const userInfo = useSelector((App) => App.userInfo);
  const storedOwner = localStorage.getItem("user_code");
  const OwnerShopId = storedOwner ? JSON.parse(storedOwner) : [];
  useEffect(() => {
    async function fetchData() {
      const formdata = new FormData();
      formdata.append("user_id",userInfo.data[0].id)
      formdata.append("user_code",OwnerShopId.user_code)
      const carts = await axios.post(
        `https://api.sellpang.com/api/getAllCartItem/`,formdata
      );
      setCartsItem(carts.data);
    }
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Sellpang</title>
        <meta name="description" content="Generated by sellpang" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cartsItem.length !== 0 ? <CartItem data={cartsItem} /> : null}
    </>
  );
}

export default useChartShop;
