import React from "react";
import Link from "next/link";
import Head from "next/head";
import { Box, Flex, Text, Image, Button, Spacer } from "@chakra-ui/react";
import ChatBox from "@/components/ChatBox";
function chat() {
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="15px">
        <ChatBox />
      </Box>
    </>
  );
}

export default chat;
