import Head from "next/head";

import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  Center,
  useDisclosure,
  Box,
  Text,
  Image,
  Input,
  Flex,
  Spacer,
  Button,
  FormControl,
  InputGroup,
  InputLeftElement,
  SimpleGrid,
  Card,
  CardHeader,
  CardBody,
  CardFooter,
  HStack,
} from "@chakra-ui/react";
import { useState, useEffect } from "react";
import { FaSearch } from "react-icons/fa";
import axios from "axios";
import Link from "next/link";
import cart from "@/public/img/icon/cart.png";
import user from "@/public/img/icon/user copy.png";
import { StarIcon } from "@chakra-ui/icons";
import StarRatings from "react-star-ratings";
export default function Home(props) {
  const {
    isOpen: isOpenForm1,
    onOpen: onOpenForm1,
    onClose: onCloseForm1,
  } = useDisclosure({ defaultIsOpen: true });
  const {
    isOpen: isOpenForm2,
    onOpen: onOpenForm2,
    onClose: onCloseForm2,
  } = useDisclosure();
  const handleClick = () => {
    onCloseForm1();
    onCloseForm2();
  };
  const loginClick = () => {
    onOpenForm2();
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal onClose={onCloseForm1} size="xs" isOpen={isOpenForm1} isCentered>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader alignSelf="flex-end" pr="10px" pt="10px">
            <Image
              src="/img/cancel.png"
              alt=""
              h="25px"
              w="25px"
              onClick={() => handleClick()}
            />
          </ModalHeader>
          <ModalBody>
            <Box px="5px">
              <Text
                bg="red"
                textAlign="center"
                borderRadius="xl"
                fontSize="25px"
                color="white"
                fontWeight="bold"
                onClick={() => loginClick()}
              >
                ลงชื่อเข้าใช้ด้วยโทรศัพท์
              </Text>
              <Text color="gray.400" textAlign="center">
                ระบบจะจดจำที่อยู่ในการส่งสินค้าเมื่อใช้งานในครั้งต่อไป
              </Text>
              <Text
                mt="15px"
                bg="gray.100"
                textAlign="center"
                borderRadius="xl"
                fontSize="25px"
                fontWeight="bold"
                onClick={() => handleClick()}
              >
                สั่งตอนนี้
              </Text>
              <Text color="gray.400" textAlign="center">
                ต้องกรอกที่อยู่ในการจัดส่งทุกครั้งที่เข้้าใช้งานใหม่
              </Text>
            </Box>
          </ModalBody>
          <ModalFooter></ModalFooter>
        </ModalContent>
      </Modal>
      <Modal onClose={onCloseForm2} size="xs" isOpen={isOpenForm2} isCentered>
        <ModalOverlay />
        <ModalContent>
          <ModalHeader alignSelf="flex-end" pr="10px" pt="10px">
            <Image
              src="/img/cancel.png"
              alt=""
              h="25px"
              w="25px"
              onClick={() => handleClick()}
            />
          </ModalHeader>
          <ModalBody>
            <Box px="5px">
              <FormControl>
                <Text fontSize="25px" fontWeight="bold">
                  กรอกเบอร์โทรศัพท์
                </Text>
                <Input bg="gray.100" />
                <Flex mt="15px">
                  <Text fontSize="25px" fontWeight="bold">
                    กรอกรหัส OTP
                  </Text>
                  <Spacer />
                  <Text fontSize="25px" color="orange" as="u">
                    รับรหัส OTP
                  </Text>
                </Flex>

                <Input bg="gray.100" />
              </FormControl>

              <Box textAlign="center">
                <Button mt="15px" bg="red" color="white" type="submit">
                  ยืนยัน
                </Button>
              </Box>
            </Box>
          </ModalBody>
          <ModalFooter></ModalFooter>
        </ModalContent>
      </Modal>
    </>
  );
}
