import { useState } from "react";
import Head from "next/head";
import { Box, Flex, SimpleGrid, Text, Button, Spacer } from "@chakra-ui/react";
import Link from "next/link";
import Product from "@/components/Product";
function product() {
  
  return (
    <>
      <Head>
        <title>product</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Product />

      <Box className="test" bottom={0}>
        <Box
          className="test"
          px="15px"
          mt="10px"
          py="8px"
          bg="white"
          pos="fixed"
          bottom={0}
        >
          <SimpleGrid
            spacing={4}
            templateColumns="repeat(2, minmax(30px, 1fr))"
            my="15px"
            fontSize="sm"
          >
            <Link href="">
              <Button w="100%" borderRadius="xl">
                <Text>เพิ่มไปยังรถเข็น</Text>
              </Button>
            </Link>
            <Link href="/order">
              <Button w="100%" bg="red" borderRadius="xl">
                <Text>ซื้อสินค้า</Text>
              </Button>
            </Link>
          </SimpleGrid>
        </Box>
      </Box>
    </>
  );
}

export default product;
