import { useState } from "react";
import Link from "next/link";
import Head from "next/head";
import { Box, Flex, Text, Image, Button, Spacer } from "@chakra-ui/react";
import Statusproduct from "@/components/statusProductProfile";
import Purchasehistory from "@/components/PurchaseHistory";
function chartShop() {
  const Product = [
    {
      item: [
        {
          shopname: "SHOPZY",
          name: "ร้องเท้าฉลาม2",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY1",
          name: "ร้องเท้าฉลาม",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY",
          name: "ร้องเท้าฉลาม",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY",
          name: "ร้องเท้าฉลาม",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
      ],
    },
    {
      item: [
        {
          shopname: "SHOPZY1",
          name: "ร้องเท้าฉลาม1",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY1",
          name: "ร้องเท้าฉลาม1",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY1",
          name: "ร้องเท้าฉลาม1",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY1",
          name: "ร้องเท้าฉลาม1",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
      ],
    },
    {
      item: [
        {
          shopname: "SHOPZY2",
          name: "ร้องเท้าฉลาม2",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY2",
          name: "ร้องเท้าฉลาม2",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY2",
          name: "ร้องเท้าฉลาม2",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
        {
          shopname: "SHOPZY2",
          name: "ร้องเท้าฉลาม2",
          detail: "น่ารักไม่ไหว ร้องเท้าแฟชั่นเกาหลี",
          image: "/img/หมาโง่.jpg",
          select: "สีฟ้า ไซด์ 42",
          num: "1",
          price: "290",
        },
      ],
    },
  ];
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex bg="white" py="25px" px="15px">
        <Box
          bg="white"
          borderRadius="50%"
          w="70px !important"
          h="70px !important"
          display="flex"
          alignItems="center"
          justifyContent="center"
          ml="2"
        >
          <Image
            borderRadius="50%"
            src="/img/icon/user copy.png"
            alt=""
            h="70px !important"
            w="70px !important"
          />
        </Box>
        <Box pl="5px">
          <Text fontSize="2xl">Username</Text>
          <Box bg="red" borderRadius="xl" fontSize="xs">
            <Text px="15px" py="3px">
              Gold member
            </Text>
          </Box>
        </Box>
        <Spacer />
        <Box alignSelf="center">
          <Link href="/address">
            <Button bg="red" borderRadius="xl" size="md" height="30px">
              <Text fontSize="xs">แก้ไขที่อยู่</Text>
            </Button>
          </Link>
        </Box>
      </Flex>
      <Box mt="10px">
        <Statusproduct data={Product} />
      </Box>

      <Purchasehistory />
    </>
  );
}

export default chartShop;
