import React from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Card,
  Flex,
  Stack,
  SimpleGrid,
  Text,
  Center,
  Image,
  CardHeader,
  CardBody,
  CardFooter,
  Button,
  Spacer,
} from "@chakra-ui/react";
function paymentQRcode() {
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="15px">
        <Box bg="white" py="10px" mt="10px">
          <Flex px="15px">
            <Box pr="15px"><Image src="/img/approval.png" h="25px" w="25px" maxWidth="none"/></Box>
            <Box>
              <Text>ข้อมูลการชำระเงิน</Text>
            </Box>
          </Flex>
          <Flex pl="60px" pr="15px">
            <Text>รวมการสั่งซื้อ</Text>
            <Spacer />
            <Text>580.-</Text>
          </Flex>
          <Flex pl="60px" pr="15px">
            <Text>ค่าจัดส่ง</Text>
            <Spacer />
            <Text>40.-</Text>
          </Flex>
          <Flex pl="60px" pr="15px">
            <Text>ยอดชำระเงินทั้งหมด</Text>
            <Spacer />
            <Text>620.-</Text>
          </Flex>
        </Box>
      </Box>
      <Box m="30px" mb="0px" bg="white" borderRadius="2xl">
        <Image src="/img/QR_code_for_mobile_English_Wikipedia.svg.png" />
      </Box>
      <Box mt="10px" display="flex" justifyContent="center">
        <Button bg="white" borderRadius="xl">
          <Text fontSize="xs">บันทึก QR CODE</Text>
        </Button>
      </Box>
      <Box m="30px" mb="0px" bg="white" borderRadius="2xl">
        <Flex alignItems="center" className="set--font" py="10px">
          <Image src="/img/icon_kbank.png" borderRadius="xl" h="14" mx="15px" />
          <Box pr="5px">
            <Text>ธนาคาร</Text>
            <Text>เลขบัญชี</Text>
            <Text>ชื่อบัญชี</Text>
          </Box>
          <Box>
            <Text>: กสิกรไทย</Text>
            <Text>: 123-4-5ุ789-0</Text>
            <Text>: นางสาวบี นามสมมุติ</Text>
          </Box>
        </Flex>
      </Box>
      <Box py="15px" px="30px" display="flex" justifyContent="end">
        <Link href="/payment/confirmPayment">
          <Button bg="red" borderRadius="xl">
            <Text>ถัดไป</Text>
          </Button>
        </Link>
      </Box>
    </>
  );
}

export default paymentQRcode;
