import { useState, useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Flex,
  Grid,
  Text,
  GridItem,
  Image,
  Button,
  Spacer,
} from "@chakra-ui/react";
import Statusproduct from "@/components/StatusProduct";
import axios from "axios";
import { connect, useDispatch, useSelector } from "react-redux";
function useStatusProduct() {
  const [orders, setOrders] = useState([]);
  const userInfo = useSelector((App) => App.userInfo);
  const storedOwner = localStorage.getItem("user_code");
  const OwnerShopId = storedOwner ? JSON.parse(storedOwner) : [];
  const [cartsItem, setCartsItem] = useState([]);
  useEffect(() => {
    async function fetchdata() {
      let user_id = userInfo.data[0].id;
      const formdataOrder = new FormData();
      formdataOrder.append("user_id", user_id);
      formdataOrder.append("user_code", OwnerShopId.user_code);
      const order = await axios.post(
        `https://api.sellpang.com/api/getAllOrder`,
        formdataOrder
      );
      setOrders(order.data.orders);
      const formdataCart = new FormData();
      formdataCart.append("user_id", userInfo.data[0].id);
      formdataCart.append("user_code", OwnerShopId.user_code);
      const carts = await axios.post(
        `https://api.sellpang.com/api/getAllCartItem/`,
        formdataCart
      );
      setCartsItem(carts.data);
    }
    fetchdata();
  }, []);
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="15px">
        <Statusproduct data={orders} carts={cartsItem}/>
      </Box>
    </>
  );
}

export default useStatusProduct;
