import { useState,useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Flex,
  Grid,
  Text,
  GridItem,
  Image,
  Button,
  Spacer,
} from "@chakra-ui/react";
import Statusproduct from "@/components/statusProduct";
import axios from "axios";
function statusProduct() {
  const [orders, setOrders] = useState([]);
  useEffect(() => {
    async function fetchdata() {
      const order = await axios.get(
        `https://shopee-api.deksilp.com/api/getOrder/?user_id=${1}&shop_id=${2}`
      );
      setOrders(order.data.orders);
    }
    fetchdata();
  }, []);
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="15px">
        <Statusproduct data={orders} />
      </Box>

      <></>
    </>
  );
}

export default statusProduct;
