import { useState,useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import {
  Box,
  Flex,
  Grid,
  Text,
  GridItem,
  Image,
  Button,
  Spacer,
} from "@chakra-ui/react";
import Statusproduct from "@/components/statusProduct";
import axios from "axios";
function useStatusProduct() {
  const [orders, setOrders] = useState([]);
  useEffect(() => {
    async function fetchdata() {
      let user_id = 1;
      let shop_id = 2;
      const formdataOrder = new FormData();
      formdataOrder.append("user_id",user_id);
      formdataOrder.append("shop_id",shop_id);
      const order = await axios.post(
        `https://shopee-api.deksilp.com/api/getAllOrder`,formdataOrder
      );
      setOrders(order.data.orders);
    }
    fetchdata();
  }, []);
  return (
    <>
      <Head>
        <title>order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box pt="15px">
        <Statusproduct data={orders} />
      </Box>
    </>
  );
}

export default useStatusProduct;
